version: "3"
services:
  backend:
    image: node:18-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "5000:5000"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app

    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
